name: "remembu-auth-filebeat"
logging.metrics.enabled: false
xpack.security.enabled: false
xpack.monitoring.enabled: false
setup.ilm.enabled: false
setup.template.enabled: false

filebeat.inputs:
- type: log
  scan_frequency: 1s
  enabled: true
  paths:
    - /src/logs/fastapi-elk-stack.*
  fields:
    - service: fastapi-app
  fields_under_root: true
  clean_removed: false # do not remove deleted logs from the registry
  close_removed: false # do not close harverster for a deleted file if it is still reading it
  clean_renamed: false # do not remove renamed files from the registry
  close_renamed: false # do not close the harvester for the renamed file if it is still reading it.
  close_inactive: 30s # close harvester after N time since the end of file reading
  clean_inactive: 90s # clean the registry for files that have been read N times ago (must be more than ignore_older + scan_frecuency)
  ignore_older: 60s # ignore collected files that are N times old.
  close_timeout: 30m #if the harvester fails to finish reading the file within N time, we will close the file in an emergency to free up resources

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "remembu-auth"
  max_retries: -1 # limit the number of attempts to send events. If events are not sent within these attempts, they will be lost. Let's switch this off

monitoring:
  enabled: true

http:
  enabled: true
  host: localhost
  port: 5066

queue.disk:
  max_size: 200GB
  path: "${path.data}/diskqueue"