version: '3.8'
services:
  postgres:
    image: postgres
    container_name: database
    environment:
      POSTGRES_PASSWORD: $PG_PASS
      POSTGRES_USER: $PG_USER
      POSTGRES_DB: $PG_DB
      PGDATA: /home/postgres/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_PASSWORD
    ports:
      - "5050:80"
    restart: unless-stopped

  fastapi:
    container_name: fastapi
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: always
    ports:
      - "8080:8000"
    expose:
      - "8080"
    volumes:
      - ./fastapi-logs:/src/logs
    environment:
      PYTHONUNBUFFERED: 1
    depends_on:
      - postgres

  filebeat:
    build:
      context: ./filebeat
    container_name: filebeat
    volumes:
      - ./fastapi-logs:/src/logs
#    depends_on:
#      - elasticsearch
#      - kibana
#      - logstash
    networks:
      - elk

volumes:
  postgres:
  fastapi:
  fastapi-logs:

networks:
  elk:
#    driver: logging_driver
    external: true