version: 1
disable_existing_loggers: false
formatters:
  default:
    (): 'uvicorn.logging.DefaultFormatter'
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  access:
    (): 'uvicorn.logging.AccessFormatter'
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
  json:
    format: '{"time": "%(asctime)s", "level": "%(levelname)s", "logger_name": "%(name)s", "message": "%(message)s"}'
  custom_json:
    (): 'src.core.jsonlogging.CustomJSONFormatter'
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: src/logs/fastapi-elk-stack.log
    maxBytes: 10485760
    backupCount: 10
    formatter: custom_json
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: custom_json
    stream: ext://sys.stdout
  default:
    formatter: custom_json
    class: logging.StreamHandler
    stream: ext://sys.stderr
  access:
    formatter: custom_json
    class: logging.StreamHandler
    stream: ext://sys.stdout
loggers:
  uvicorn.error:
    level: INFO
    handlers:
      - default
      - file
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - access
      - file
    propagate: no
root:
  handlers:
    - file
  level: DEBUG
