version: 1
disable_existing_loggers: false
formatters:
  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"
handlers:
  file:
    class: logging.handlers.RotatingFileHandler
    filename: src/logs/fastapi-elk-stack.log
    maxBytes: 10485760
    backupCount: 10
    formatter: standard
    level: DEBUG
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout
root:
  handlers:
    - file
    - console
  level: DEBUG
